#!/bin/sh

if [ "$1" = "/" ]; then
    echo 'ino=1 mode=drwxr-xr-x nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
elif [ "$1" = "/README" ]; then
    echo 'ino=1 mode=-rwxr-xr-x nlink=1 uid=0 gid=0 rdev=0 size=1111 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
elif [ "$1" = "/createme" ]; then
    if [ -e /tmp/create_me  ]; then
        printf 'ino=1 mode=-rwxr-xr-x nlink=1 uid=0 gid=0 rdev=0 size='
        find /tmp/create_me -printf '%s'
        printf ' blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
    else
        exit 1
    fi
else
    exit 1
fi
