#!/bin/sh
# Optional script: if not implemented, write_file will be called for any file
# Arguments: path mode

# If something echo'ed here, execfuse will try to open that file to create, and
# further file operations on file descriptor will be performed against that open file.
# Eg.
# echo "$HOME/.cache/$1"

exit 0
