#!/bin/bash

EFV="$1"
VIDEO="$2"
true ${FFMPEG:="ffmpeg"}
true ${TMPDIR:="/tmp"}

if [ "$EFV" != "0" ]; then
    echo "video_frames expects execfuse API version 0" >&2
fi


VID=$(ffmpeg -fdebug ts -i "$VIDEO" 2>&1 | grep Video)

if [ -z "$VID" ]; then
    echo "Failed to read video parameters"
    echo "Check if this command works for you:"
    echo "$FFMPEG -fdebug ts -i $VIDEO"
    exit 1;
fi

VIDHW=$(echo $VID | grep -o '[0-9]\+x[0-9]\+')
IFS="x" read W H <<< "$VIDHW"
FRAMESIZE=$((W*H*4+100))

echo "Video resolution $W x $H; Video frame size $FRAMESIZE"

mkdir -p $TMPDIR/video_frames.$EXECFUSE_PID
echo $FRAMESIZE > $TMPDIR/video_frames.$EXECFUSE_PID/videoframesize


#echo "$TMPDIR $FFMPEG $VIDEO $EFV $EXECFUSE_PID"

exit 0
